version: '3.7'
services:
    mirakurun:
        container_name: mirakurun
        image: ghcr.io/kanagawa-iamtakagi-net/mirakurun:latest
        cap_add:
            - SYS_ADMIN
            - SYS_NICE
        ports:
            - "40772:40772"
            - "9229:9229"
        volumes:
            - ./mirakurun/container-init.sh:/app/container-init.sh
            - ./mirakurun/conf:/app-config
            - ./mirakurun/data:/app-data
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/px4video0:/dev/px4video0
            - /dev/px4video1:/dev/px4video1
            - /dev/px4video2:/dev/px4video2
            - /dev/px4video3:/dev/px4video3
            - /dev/bus:/dev/bus
        restart: always
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m

    mysql:
        image: mariadb:10.5
        # image: mysql:8.0 # 囲み文字を使用する場合
        volumes:
            - mysql-db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation
            TZ: "Asia/Tokyo"
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1 # for mariadb
        # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --performance-schema=false --expire_logs_days=1 --default-authentication-plu=mysql_native_password # for myql
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    epgstation:
        container_name: epgstation
        image: ghcr.io/kanagawa-iamtakagi-net/epgstation:latest
        build: 
            context: ./epgstation
            dockerfile: Dockerfile.debian
        volumes:
            - ./epgstation/config:/app/config
            - ./epgstation/data:/app/data
            - ./epgstation/thumbnail:/app/thumbnail
            - ./epgstation/logs:/app/logs
            - ./epgstation/config/EPGS-to-Discord.env:/app/EPGS-to-Discord-v2/.env
            - /mnt/disk1/recorded:/app/recorded
        environment:
            TZ: "Asia/Tokyo"
        depends_on:
            - mirakurun
            - mysql
        ports:
            - "8888:8888"
            - "8889:8889"
#         user: "1000:1000"
#         devices:
#             - /dev/dri:/dev/dri
        restart: always
    
    konomitv:
        image: konomitv
        container_name: KonomiTV
        restart: always
        build:
            context: ./KonomiTV
            dockerfile: Dockerfile
        #deploy:
            #resources:
                #reservations:
                    #devices:
                        #- driver: nvidia
                          #capabilities: [compute, utility, video]
        #devices:
            #- '/dev/dri:/dev/dri'
        volumes:
            - type: bind
              source: './KonomiTV/config.yaml'
              target: '/code/config.yaml'
            - type: bind
              source: './KonomiTV/client/'
              target: '/code/client/'
            - type: bind
              source: './KonomiTV/server/app/'
              target: '/code/server/app/'
            - type: bind
              source: './KonomiTV/server/data/'
              target: '/code/server/data/'
            - type: bind
              source: './KonomiTV/server/logs/'
              target: '/code/server/logs/'
        ports:
            - '7000:7000'

volumes:
    mysql-db:
        driver: local

